#ifndef GUI_H
#define GUI_H
// GUI element IDs:
enum {
	GAME_USER_INTERFACE_WINDOW,
	GAME_USER_INTERFACE_QUIT_BUTTON,
	GAME_USER_INTERFACE_TEXT_WINDOW,
	MAIN_MENU_WINDOW,
	MAIN_MENU_JOIN_BUTTON,
	MAIN_MENU_SERVER_BUTTON,
	MAIN_MENU_EDITOR_BUTTON,
	MAIN_MENU_QUIT_BUTTON,
	EDITOR_WINDOW,
	EDITOR_SAVE_BUTTON,
	EDITOR_QUIT_BUTTON
};

#endif

